# Generated by Django 6.0.1 on 2026-02-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tenant_contact_cycle_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_cycle_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
