# Generated by Django 6.0.1 on 2026-01-12 14:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('nip', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('classification', models.CharField(blank=True, max_length=120)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('last_invoice_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=120)),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_date', models.DateField(default=django.utils.timezone.now)),
                ('next_contact_at', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=255)),
                ('current_comment', models.TextField(blank=True)),
                ('previous_comment', models.TextField(blank=True)),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='accounts.tenant')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_records', to='core.client')),
            ],
            options={
                'ordering': ('-contact_date',),
            },
        ),
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_drive_minutes', models.PositiveIntegerField(default=0)),
                ('total_visit_minutes', models.PositiveIntegerField(default=0)),
                ('shared_with_manager', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='accounts.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('drive_minutes', models.PositiveIntegerField(default=0)),
                ('visit_minutes', models.PositiveIntegerField(default=30)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='core.client')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.routeplan')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(default='planned', max_length=32)),
                ('comment', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.client')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='accounts.tenant')),
            ],
            options={
                'ordering': ('-planned_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('comment_type', models.CharField(choices=[('pre', 'Pre-visit'), ('post', 'Post-visit')], max_length=16)),
                ('is_editable', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.tenant')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='core.routeplan')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='core.visit')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'name'], name='core_client_tenant__34dc86_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'nip'], name='core_client_tenant__77ad6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('tenant', 'nip')},
        ),
        migrations.AlterUniqueTogether(
            name='routestop',
            unique_together={('route', 'order')},
        ),
    ]
