# Generated by Django 6.0.1 on 2026-01-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_importjob_importrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
