# Generated by Django 6.0.1 on 2026-01-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_importjob_cancel_requested_alter_importjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='failed_geocode_log',
            field=models.FileField(blank=True, upload_to='import_logs/'),
        ),
    ]
