# Generated by Django 6.0.1 on 2026-01-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_importjob_failed_geocode_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrecord',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='importrecord',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='importrecord',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
