# Generated by Django 6.0.1 on 2026-01-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_importrecord_city_importrecord_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importrecord',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='importrecord',
            name='street',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
