# Generated by Django 6.0.1 on 2026-01-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_route_stop_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='location_accuracy',
            field=models.FloatField(blank=True, help_text='Accuracy in meters reported by the device GPS.', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
