# Generated by Django 6.0.1 on 2026-01-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_visit_latitude_visit_location_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
