# Generated by Django 6.0.1 on 2026-01-26 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0010_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='core_client_tenant__77ad6c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('tenant', 'nip', 'city')},
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tenant', 'nip', 'city'], name='core_client_tenant__4cf236_idx'),
        ),
    ]
