# Generated by Django 6.0.1 on 2026-01-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_client_core_client_tenant__77ad6c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_reminder_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
