# Generated by Django 6.0.1 on 2026-02-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_client_contact_reminder_days_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_days_label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
