# Generated by Django 6.0.1 on 2026-02-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_client_contact_days_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_days_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
