# Generated by Django 6.0.1 on 2026-02-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_client_contact_cycle_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
