# Generated by Django 6.0.1 on 2026-02-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_client_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='upload_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
