# Generated by Django 6.0.1 on 2026-02-11 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_importjob_upload_blob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routeplan',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Do akceptacji'), ('approved', 'Zaakceptowana'), ('rejected', 'Odrzucona')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_routes', to=settings.AUTH_USER_MODEL),
        ),
    ]
