# Generated by Django 6.0.1 on 2026-02-12 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_contact_cycle_start_date'),
        ('core', '0019_routeplan_approval_status_routeplan_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Nowe'), ('in_progress', 'W trakcie'), ('awaiting_review', 'Do potwierdzenia'), ('completed', 'Zamknięte'), ('cancelled', 'Anulowane')], default='pending', max_length=32)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.tenant')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_completion', models.BooleanField(default=False)),
                ('is_manager_reply', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_messages', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.task')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='core_taskmessage' AND column_name='is_completion') THEN
                    ALTER TABLE core_taskmessage ADD COLUMN is_completion boolean NOT NULL DEFAULT false;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='core_taskmessage' AND column_name='is_manager_reply') THEN
                    ALTER TABLE core_taskmessage ADD COLUMN is_manager_reply boolean NOT NULL DEFAULT false;
                END IF;
            END$$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='core_taskmessage' AND column_name='is_completion') THEN
                    ALTER TABLE core_taskmessage DROP COLUMN is_completion;
                END IF;
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='core_taskmessage' AND column_name='is_manager_reply') THEN
                    ALTER TABLE core_taskmessage DROP COLUMN is_manager_reply;
                END IF;
            END$$;
            """,
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'assigned_to', 'status'], name='core_task_assignee_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'client'], name='core_task_tenant_client'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant', 'due_date'], name='core_task_due_date'),
        ),
    ]
