# Generated by Django 6.0.1 on 2026-02-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_core_task_assignee_status_core_task_tenant__61bf4e_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='core_taskmessage' AND column_name='is_completion') THEN
                    ALTER TABLE core_taskmessage ADD COLUMN is_completion boolean NOT NULL DEFAULT false;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='core_taskmessage' AND column_name='is_manager_reply') THEN
                    ALTER TABLE core_taskmessage ADD COLUMN is_manager_reply boolean NOT NULL DEFAULT false;
                END IF;
            END$$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='core_taskmessage' AND column_name='is_completion') THEN
                    ALTER TABLE core_taskmessage DROP COLUMN is_completion;
                END IF;
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='core_taskmessage' AND column_name='is_manager_reply') THEN
                    ALTER TABLE core_taskmessage DROP COLUMN is_manager_reply;
                END IF;
            END$$;
            """,
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_assignee_status') THEN
                    ALTER INDEX core_task_assignee_status RENAME TO core_task_tenant__61bf4e_idx;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_tenant_client') THEN
                    ALTER INDEX core_task_tenant_client RENAME TO core_task_tenant__9305a8_idx;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_due_date') THEN
                    ALTER INDEX core_task_due_date RENAME TO core_task_tenant__6902a5_idx;
                END IF;
            END$$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_tenant__61bf4e_idx') THEN
                    ALTER INDEX core_task_tenant__61bf4e_idx RENAME TO core_task_assignee_status;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_tenant__9305a8_idx') THEN
                    ALTER INDEX core_task_tenant__9305a8_idx RENAME TO core_task_tenant_client;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_tenant__6902a5_idx') THEN
                    ALTER INDEX core_task_tenant__6902a5_idx RENAME TO core_task_due_date;
                END IF;
            END$$;
            """,
        ),
    ]
