# Generated by Django 6.0.1 on 2026-02-12 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_contact_cycle_start_date'),
        ('core', '0022_rename_core_task_assignee_status_core_task_tenant__61bf4e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='core_taskmessage' AND column_name='status_snapshot') THEN
                    ALTER TABLE core_taskmessage ADD COLUMN status_snapshot varchar(32) DEFAULT '' NOT NULL;
                END IF;
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='core_taskmessage' AND column_name='due_date_update') THEN
                    ALTER TABLE core_taskmessage ADD COLUMN due_date_update date NULL;
                END IF;
            END$$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='core_taskmessage' AND column_name='status_snapshot') THEN
                    ALTER TABLE core_taskmessage DROP COLUMN status_snapshot;
                END IF;
                IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='core_taskmessage' AND column_name='due_date_update') THEN
                    ALTER TABLE core_taskmessage DROP COLUMN due_date_update;
                END IF;
            END$$;
            """,
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_assignee_status') THEN
                    ALTER INDEX core_task_assignee_status RENAME TO core_task_tenant__61bf4e_idx;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_tenant_client') THEN
                    ALTER INDEX core_task_tenant_client RENAME TO core_task_tenant__9305a8_idx;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_due_date') THEN
                    ALTER INDEX core_task_due_date RENAME TO core_task_tenant__6902a5_idx;
                END IF;
            END$$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_tenant__61bf4e_idx') THEN
                    ALTER INDEX core_task_tenant__61bf4e_idx RENAME TO core_task_assignee_status;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_tenant__9305a8_idx') THEN
                    ALTER INDEX core_task_tenant__9305a8_idx RENAME TO core_task_tenant_client;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_tenant__6902a5_idx') THEN
                    ALTER INDEX core_task_tenant__6902a5_idx RENAME TO core_task_due_date;
                END IF;
            END$$;
            """,
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'W kolejce'), ('running', 'W trakcie'), ('success', 'Zakończony'), ('error', 'Błąd')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, upload_to='backups/%Y/%m/%d/')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_jobs', to='accounts.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
