# Generated by Django 6.0.1 on 2026-02-27 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_core_task_assignee_status_core_task_tenant__61bf4e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrecord',
            options={'ordering': ('-contact_date', '-contact_time')},
        ),
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_assignee_status') THEN
                    ALTER INDEX core_task_assignee_status RENAME TO core_task_tenant__61bf4e_idx;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_tenant_client') THEN
                    ALTER INDEX core_task_tenant_client RENAME TO core_task_tenant__9305a8_idx;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'core_task_due_date') THEN
                    ALTER INDEX core_task_due_date RENAME TO core_task_tenant__6902a5_idx;
                END IF;
            END$$;
            """,
            reverse_sql="",
        ),
        migrations.AddField(
            model_name='callrecord',
            name='contact_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='taskmessage',
            name='due_date_update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmessage',
            name='status_snapshot',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
