# Generated by Django 6.0.1 on 2026-02-27 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_core_task_assignee_status_core_task_tenant__61bf4e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrecord',
            options={'ordering': ('-contact_date', '-contact_time')},
        ),
        migrations.AddField(
            model_name='callrecord',
            name='contact_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
