# Generated by Django 6.0.1 on 2026-02-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_contact_time'),
        ('core', '0025_alter_callrecord_options_and_more'),
    ]

    operations = [
    ]
