# Generated by Django 6.0.1 on 2026-02-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20260227_1412'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE core_callrecord ADD COLUMN IF NOT EXISTS contact_time time DEFAULT '12:00:00'::time NOT NULL;",
            reverse_sql="ALTER TABLE core_callrecord DROP COLUMN IF EXISTS contact_time;",
        ),
    ]
