# Generated by Django 6.0.1 on 2026-05-25 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_contact_cycle_start_date'),
        ('core', '0028_client_deleted_at_client_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNextDateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_days', models.PositiveIntegerField()),
                ('proposed_days', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Oczekujący'), ('approved', 'Zatwierdzony'), ('rejected', 'Odrzucony')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('call_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_date_requests', to='core.callrecord')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_date_requests', to='core.client')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_next_date_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_contact_next_date_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_next_date_requests', to='accounts.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('call_record',), name='unique_pending_contact_next_date_request')],
            },
        ),
    ]
